<template>
  <div class="popCard" :class="show ? 'on' : ''">
    <div class="inHead">
      <p>设备添加</p>
      <a class="btn" @click.stop="$emit('update:show', false)">
        <img src="@/assets/close.svg" class="icon" alt="" />
        <img src="@/assets/close2.svg" class="hov" alt="" />
      </a>
      <div class="bottom">
        <div class="icon"></div>
        <div class="icon2"></div>
        <div class="icon3"></div>
        <div class="bd"></div>
      </div>
    </div>

    <div class="inBody">
      <h2 class="title">添加新设备</h2>
      <p class="hint">请在地图上点击位置来添加设备</p>

      <div class="infoCard" v-if="newDevice.position">
        <div class="infoItem">
          <h2 class="label">点击位置：</h2>
          <p class="value">{{ newDevice.position[0] ? newDevice.position[0].toFixed(6) : "-" }}, {{ newDevice.position[1] ? newDevice.position[1].toFixed(6) : "-" }}</p>
        </div>
      </div>

      <div class="itemCard">
        <h2 class="name">设备类型</h2>
        <div class="selectCard" :class="selectSlide ? 'on' : ''">
          <div class="label" @click.stop="toggleDeviceType">
            <p>{{ getDeviceTypeName(newDevice.pointType) }}</p>
            <img src="@/assets/slide.png" alt="" />
          </div>
          <div class="slideCard">
            <div class="inBox">
              <div class="list">
                <a class="item" @click.stop="setDeviceType(1)">阀门</a>
                <a class="item" @click.stop="setDeviceType(2)">排水阀</a>
                <a class="item" @click.stop="setDeviceType(5)">流量计</a>
                <a class="item" @click.stop="setDeviceType(7)">水池</a>
                <a class="item" @click.stop="setDeviceType(8)">水泵</a>
                <a class="item" @click.stop="setDeviceType(0)">压力计</a>
                <a class="item" @click.stop="setDeviceType(10)">弯头</a>
                <a class="item" @click.stop="setDeviceType(20)">三通</a>
                <a class="item" @click.stop="setDeviceType(30)">四通</a>
                <a class="item" @click.stop="setDeviceType(31)">消防栓</a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="itemCard">
        <h2 class="name">设备名称</h2>
        <input type="text" v-model="newDevice.name" :placeholder="isNameAutoGenerated ? '设备名称将根据设备类型自动生成' : '请输入设备名称'" :readonly="isNameAutoGenerated" class="input" />
      </div>

      <!-- 水泵专用字段 -->
      <template v-if="newDevice.pointType === 8">
        <div class="itemCard">
          <h2 class="name">状态</h2>
          <div class="selectCard" :class="selectSlideStatus ? 'on' : ''">
            <div class="label" @click.stop="toggleStatus">
              <p>{{ newDevice.status || "请选择状态" }}</p>
              <img src="@/assets/slide.png" alt="" />
            </div>
            <div class="slideCard">
              <div class="inBox">
                <div class="list">
                  <a class="item" @click.stop="setStatus('开')">开</a>
                  <a class="item" @click.stop="setStatus('关')">关</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="itemCard">
          <h2 class="name">电压 (V)</h2>
          <input type="number" v-model="newDevice.voltage" placeholder="请输入电压" class="input" />
        </div>
        <div class="itemCard">
          <h2 class="name">电流 (A)</h2>
          <input type="number" v-model="newDevice.electricity" placeholder="请输入电流" class="input" />
        </div>
        <div class="itemCard">
          <h2 class="name">设备唯一标识</h2>
          <input type="text" v-model="newDevice.deviceId" placeholder="请输入设备唯一标识" class="input" />
        </div>
      </template>

      <!-- 阀门专用字段 -->
      <template v-if="newDevice.pointType === 1">
        <div class="itemCard">
          <h2 class="name">口径 (mm)</h2>
          <input type="number" v-model="newDevice.caliber" placeholder="请输入口径" class="input" />
        </div>
        <div class="itemCard">
          <h2 class="name">类型</h2>
          <div class="selectCard" :class="selectSlideType ? 'on' : ''">
            <div class="label" @click.stop="toggleValveType">
              <p>{{ newDevice.valveType || "请选择类型" }}</p>
              <img src="@/assets/slide.png" alt="" />
            </div>
            <div class="slideCard">
              <div class="inBox">
                <div class="list">
                  <a class="item" @click.stop="setValveType('进水阀')">进水阀</a>
                  <a class="item" @click.stop="setValveType('放空阀')">放空阀</a>
                  <a class="item" @click.stop="setValveType('落水阀')">落水阀</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="itemCard">
          <h2 class="name">状态</h2>
          <div class="selectCard" :class="selectSlideStatus ? 'on' : ''">
            <div class="label" @click.stop="toggleStatus">
              <p>{{ newDevice.status || "请选择状态" }}</p>
              <img src="@/assets/slide.png" alt="" />
            </div>
            <div class="slideCard">
              <div class="inBox">
                <div class="list">
                  <a class="item" @click.stop="setStatus('开')">开</a>
                  <a class="item" @click.stop="setStatus('关')">关</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="itemCard">
          <h2 class="name">设备唯一标识</h2>
          <input type="text" v-model="newDevice.deviceId" placeholder="请输入设备唯一标识" class="input" />
        </div>
      </template>

      <!-- 流量计专用字段 -->
      <template v-if="newDevice.pointType === 5">
        <div class="itemCard">
          <h2 class="name">口径 (mm)</h2>
          <input type="number" v-model="newDevice.caliber" placeholder="请输入口径" class="input" />
        </div>
        <div class="itemCard">
          <h2 class="name">表号</h2>
          <input type="text" v-model="newDevice.meterNumber" placeholder="请输入表号" class="input" />
        </div>
      </template>

      <!-- 水池专用字段 -->
      <template v-if="newDevice.pointType === 7">
        <div class="itemCard">
          <h2 class="name">设备唯一标识</h2>
          <input type="text" v-model="newDevice.deviceId" placeholder="请输入设备唯一标识" class="input" />
        </div>
        <div class="itemCard">
          <h2 class="name">深度 (米)</h2>
          <input type="number" v-model="newDevice.depth" placeholder="请输入深度" class="input" />
        </div>
      </template>

      <!-- 压力计专用字段 -->
      <template v-if="newDevice.pointType === 0">
        <div class="itemCard">
          <h2 class="name">压力值 (MPa)</h2>
          <input type="number" v-model="newDevice.pressure" placeholder="请输入压力值" class="input" />
        </div>
        <div class="itemCard">
          <h2 class="name">设备唯一标识</h2>
          <input type="text" v-model="newDevice.deviceId" placeholder="请输入设备唯一标识" class="input" />
        </div>
      </template>
    </div>

    <div class="saveCard">
      <a class="btn" @click.stop="save">
        <img src="@/assets/coordinate/icon1.svg" alt="" />
        <p>保 存</p>
      </a>
    </div>
  </div>
</template>

<script setup>
import { ElMessage } from "element-plus";
import { reactive, defineProps, ref, onMounted, onBeforeUnmount, defineEmits, getCurrentInstance, watch, computed } from "vue";
const { proxy } = getCurrentInstance();
const emit = defineEmits(["update:show", "deviceAdded"]);

const props = defineProps(["show", "allTownSelect", "clickPosition"]);

const selectSlide = ref(false);
const selectSlideStatus = ref(false);
const selectSlideType = ref(false);

onMounted(() => {
  document.body.addEventListener("click", (e) => {
    selectSlide.value = false;
    selectSlideStatus.value = false;
    selectSlideType.value = false;
  });
});

onBeforeUnmount(() => {
  document.body.removeEventListener("click", (e) => {
    selectSlide.value = false;
    selectSlideStatus.value = false;
    selectSlideType.value = false;
  });
});

const newDevice = reactive({
  pointType: 1, // 默认阀门
  name: "阀门", // 默认设备名称（根据设备类型自动设置）
  position: null, // [lng, lat]
  rotationAngle: 0,
  // 水泵字段
  status: "", // 开/关
  voltage: "", // 电压
  electricity: "", // 电流
  deviceId: "", // 设备唯一标识
  // 阀门字段
  caliber: "", // 口径
  valveType: "", // 类型：进水阀、放空阀、落水阀
  // 流量计字段
  meterNumber: "", // 表号
  // 水池字段
  depth: "", // 深度
  // 压力计字段
  pressure: "", // 压力值
});

// 计算属性：判断当前设备类型是否需要自动生成名称
const isNameAutoGenerated = computed(() => {
  return isAutoGeneratedName(newDevice.pointType);
});

// 监听弹窗打开，重置表单（优先执行）
watch(
  () => props.show,
  (isShow) => {
    if (isShow) {
      // 打开时重置表单
      newDevice.pointType = 1;
      // 根据设备类型决定是否自动设置名称（默认是阀门，固定名称）
      newDevice.name = getDeviceTypeName(1); // 阀门是固定名称，自动设置
      newDevice.rotationAngle = 0;
      newDevice.position = null; // 清除位置
      resetDeviceFields();
      // 重置所有下拉框状态
      selectSlide.value = false;
      selectSlideStatus.value = false;
      selectSlideType.value = false;
    } else {
      // 关闭时清除位置和所有字段
      newDevice.position = null;
      resetDeviceFields();
    }
  },
  { immediate: true } // 立即执行一次，确保初始化时清除位置
);

// 监听点击位置变化（只在弹窗打开时更新位置）
watch(
  () => props.clickPosition,
  (newPos) => {
    // 只有当弹窗打开且有新位置时才更新
    if (props.show && newPos) {
      newDevice.position = Array.isArray(newPos) ? [...newPos] : [newPos.lng || newPos.getLng(), newPos.lat || newPos.getLat()];
    }
  },
  { deep: true }
);

function getDeviceTypeName(type) {
  const typeMap = {
    1: "阀门",
    2: "排水阀",
    5: "流量计",
    7: "水池",
    8: "水泵",
    0: "压力计",
    10: "弯头",
    20: "三通",
    30: "四通",
    31: "消防栓",
  };
  return typeMap[type] || "请选择设备类型";
}

// 判断设备类型是否需要自动生成名称
// 固定名称：水泵(8)、阀门(1)、流量计(5)、水池(7)、压力计(0)
// 用户输入：弯头(10)、三通(20)、四通(30)、消防栓(31)、排水阀(2)
function isAutoGeneratedName(type) {
  // 固定名称的设备类型
  const fixedNameTypes = [0, 1, 5, 7, 8]; // 压力计、阀门、流量计、水池、水泵
  return fixedNameTypes.includes(type);
}

function setDeviceType(type) {
  newDevice.pointType = type;
  // 根据设备类型决定是否需要自动设置名称
  if (isAutoGeneratedName(type)) {
    // 固定名称的设备类型，自动设置名称
    newDevice.name = getDeviceTypeName(type);
  } else {
    // 需要用户输入的设备类型，清空名称让用户填写
    newDevice.name = "";
  }
  selectSlide.value = false;
  // 关闭其他下拉框
  selectSlideStatus.value = false;
  selectSlideType.value = false;
  // 切换设备类型时，清空其他类型的字段
  resetDeviceFields();
}

function resetDeviceFields() {
  // 清空所有字段
  newDevice.status = "";
  newDevice.voltage = "";
  newDevice.electricity = "";
  newDevice.deviceId = "";
  newDevice.caliber = "";
  newDevice.valveType = "";
  newDevice.meterNumber = "";
  newDevice.depth = "";
  newDevice.pressure = "";
}

function setStatus(value) {
  newDevice.status = value;
  selectSlideStatus.value = false;
  // 关闭其他下拉框
  selectSlide.value = false;
  selectSlideType.value = false;
}

function toggleDeviceType() {
  selectSlide.value = !selectSlide.value;
  // 关闭其他下拉框
  if (selectSlide.value) {
    selectSlideStatus.value = false;
    selectSlideType.value = false;
  }
}

function toggleStatus() {
  selectSlideStatus.value = !selectSlideStatus.value;
  // 关闭其他下拉框
  if (selectSlideStatus.value) {
    selectSlide.value = false;
    selectSlideType.value = false;
  }
}

function toggleValveType() {
  selectSlideType.value = !selectSlideType.value;
  // 关闭其他下拉框
  if (selectSlideType.value) {
    selectSlide.value = false;
    selectSlideStatus.value = false;
  }
}

function setValveType(value) {
  newDevice.valveType = value;
  selectSlideType.value = false;
  // 关闭其他下拉框
  selectSlide.value = false;
  selectSlideStatus.value = false;
}

async function save() {
  // 根据设备类型验证或设置设备名称
  if (isAutoGeneratedName(newDevice.pointType)) {
    // 固定名称的设备类型，确保名称已设置
    if (!newDevice.name) {
      newDevice.name = getDeviceTypeName(newDevice.pointType);
    }
  } else {
    // 需要用户输入的设备类型，验证名称是否填写
    if (!newDevice.name || newDevice.name.trim() === "") {
      ElMessage.warning("请输入设备名称");
      return;
    }
  }

  if (!newDevice.position || !Array.isArray(newDevice.position) || newDevice.position.length < 2) {
    ElMessage.warning("请在地图上点击位置来添加设备");
    return;
  }

  if (!props.allTownSelect) {
    ElMessage.warning("请选择所属区域");
    return;
  }

  // 根据设备类型验证必填字段
  if (newDevice.pointType === 8) {
    // 水泵
    if (!newDevice.status) {
      ElMessage.warning("请选择状态");
      return;
    }
    if (!newDevice.voltage) {
      ElMessage.warning("请输入电压");
      return;
    }
    if (!newDevice.electricity) {
      ElMessage.warning("请输入电流");
      return;
    }
    if (!newDevice.deviceId) {
      ElMessage.warning("请输入设备唯一标识");
      return;
    }
  } else if (newDevice.pointType === 1) {
    // 阀门
    if (!newDevice.caliber) {
      ElMessage.warning("请输入口径");
      return;
    }
    if (!newDevice.valveType) {
      ElMessage.warning("请选择类型");
      return;
    }
    if (!newDevice.status) {
      ElMessage.warning("请选择状态");
      return;
    }
    if (!newDevice.deviceId) {
      ElMessage.warning("请输入设备唯一标识");
      return;
    }
  } else if (newDevice.pointType === 5) {
    // 流量计
    if (!newDevice.caliber) {
      ElMessage.warning("请输入口径");
      return;
    }
    if (!newDevice.meterNumber) {
      ElMessage.warning("请输入表号");
      return;
    }
  } else if (newDevice.pointType === 7) {
    // 水池
    if (!newDevice.deviceId) {
      ElMessage.warning("请输入设备唯一标识");
      return;
    }
    if (!newDevice.depth) {
      ElMessage.warning("请输入深度");
      return;
    }
  } else if (newDevice.pointType === 0) {
    // 压力计
    if (!newDevice.pressure) {
      ElMessage.warning("请输入压力值");
      return;
    }
    if (!newDevice.deviceId) {
      ElMessage.warning("请输入设备唯一标识");
      return;
    }
  }

  // 验证位置是否存在
  if (!newDevice.position || !Array.isArray(newDevice.position) || newDevice.position.length < 2) {
    ElMessage.warning("请在地图上点击位置来添加设备");
    return;
  }

  try {
    // 构建 properties 对象
    const properties = {
      name: newDevice.name,
      point_type: newDevice.pointType,
      city_town: props.allTownSelect,
    };

    // 根据设备类型添加对应的字段
    if (newDevice.pointType === 8) {
      // 水泵
      properties.shuibeng_status = newDevice.status;
      properties.shuibeng_dianliu = newDevice.electricity; // 电流 (electricity)
      properties.shuibeng_dianya = newDevice.voltage; // 电压 (voltage)
      properties.shuibeng_only = newDevice.deviceId;
    } else if (newDevice.pointType === 1) {
      // 阀门
      properties.caliber = newDevice.caliber;
      properties.famen_type = newDevice.valveType;
      properties.famen_status = newDevice.status;
      properties.famen_only = newDevice.deviceId;
    } else if (newDevice.pointType === 5) {
      // 流量计
      properties.caliber = newDevice.caliber;
      properties.imei = newDevice.meterNumber;
    } else if (newDevice.pointType === 7) {
      // 水池
      properties.shuichi_only = newDevice.deviceId;
      properties.depth = newDevice.depth;
    } else if (newDevice.pointType === 0) {
      // 压力计
      properties.elevation = newDevice.pressure;
      properties.yaliji_only = newDevice.deviceId;
    } else if (newDevice.pointType === 10) {
      // 弯头
      properties.rotation_angle = 0;
    } else if (newDevice.pointType === 20) {
      // 三通
      properties.rotation_angle = 0;
    } else if (newDevice.pointType === 30) {
      // 四通
      properties.rotation_angle = 0;
    }

    // 构建 GeoJSON Feature 格式的数据
    const geoJsonData = {
      commitType: "提交",
      features: [
        {
          type: "Feature",
          properties: properties,
          geometry: {
            type: "Point",
            coordinates: newDevice.position, // [lng, lat]
          },
        },
      ],
    };

    // 调用添加设备API
    const { code, msg } = await proxy.ajax.post("/DBAllDataPostWeb", geoJsonData, true);

    if (code === 200) {
      ElMessage.success("设备添加成功！");
      // 重置表单（在emit之前重置，确保回调时状态已清空）
      newDevice.rotationAngle = 0;
      newDevice.position = null;
      resetDeviceFields();
      // 根据当前设备类型重新设置设备名称
      if (isAutoGeneratedName(newDevice.pointType)) {
        // 固定名称的设备类型，自动设置名称
        newDevice.name = getDeviceTypeName(newDevice.pointType);
      } else {
        // 需要用户输入的设备类型，清空名称
        newDevice.name = "";
      }
      // 触发父组件回调，刷新地图设备
      emit("deviceAdded", geoJsonData);
    } else {
      ElMessage.error(msg || "添加失败");
    }
  } catch (error) {
    console.error("添加设备失败:", error);
    ElMessage.error("添加失败，请重试");
  }
}
</script>

<style lang="scss" scoped>
.popCard {
  position: absolute;
  right: 180px;
  bottom: 20px;
  top: 20px;
  width: 430px;
  background: #fff;
  z-index: 200;
  display: flex;
  flex-direction: column;
  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  transform: translateX(50px);
  pointer-events: none;
  opacity: 0;
  transition: all 0.2s;
  &.on {
    transform: translateX(0px);
    pointer-events: auto;
    opacity: 1;
  }
  .inHead {
    height: 50px;
    min-height: 50px;
    display: flex;
    align-items: center;
    padding: 0 20px;
    position: relative;
    p {
      font-size: 22px;
      color: #585657;
    }
    a {
      margin-left: auto;
      width: 14px;
      height: 14px;
      position: relative;
      display: flex;
      align-items: center;
      justify-content: center;
      img {
        width: 100%;
        height: 100%;
        &.hov {
          position: absolute;
          width: 100%;
          height: 100%;
          left: 0;
          top: 0;
          opacity: 0;
        }
      }
      &:hover {
        img {
          &.hov {
            opacity: 1;
          }
        }
      }
    }
    .bottom {
      position: absolute;
      pointer-events: none;
      left: 20px;
      right: 20px;
      bottom: -3px;
      display: flex;
      align-items: center;
      height: 5px;
      .icon {
        width: 4px;
        height: 4px;
        margin-right: 8px;
        background: #46b97e;
      }
      .icon2 {
        width: 4px;
        height: 4px;
        margin-right: 8px;
        background: #90d5b2;
      }
      .icon3 {
        width: 4px;
        height: 4px;
        margin-right: 8px;
        background: #c7ead8;
      }
      .bd {
        flex: 1;
        height: 1px;
        background: #e9e9e9;
      }
    }
  }
  .inBody {
    display: flex;
    flex-direction: column;
    overflow-y: auto;
    flex: 1;
    padding: 20px;
    &::-webkit-scrollbar {
      width: 8px;
    }
    &::-webkit-scrollbar-thumb {
      border-radius: 6px;
      background: #b5e3cb;
      width: 8px;
    }
  }
}

.title {
  font-size: 20px;
  color: #585657;
  line-height: 32px;
  height: 32px;
  margin-bottom: 10px;
}

.hint {
  font-size: 18px;
  color: #999;
  margin-bottom: 20px;
  padding: 10px;
  background: #f5f5f5;
  border-radius: 6px;
}

.infoCard {
  margin-bottom: 20px;
  padding: 15px;
  background: #ecf8f2;
  border-radius: 6px;
}

.infoItem {
  display: flex;
  align-items: center;
  .label {
    font-size: 20px;
    color: #606060;
    margin-right: 10px;
    min-width: 100px;
  }
  .value {
    font-size: 20px;
    color: #333;
    word-break: break-all;
  }
}

.selectCard {
  position: relative;
  z-index: 10;
  display: flex;
  align-items: center;
  height: 40px;
  flex: 0;
  border: 1px solid #eaeaea;
  width: 100%;
  border-radius: 6px;
  margin-bottom: 15px;
  &.on {
    z-index: 100; // 打开时提高层级
    .slideCard {
      top: 30px;
      opacity: 1;
      pointer-events: auto;
      z-index: 100; // 下拉菜单也要提高层级
    }
    img {
      transform: rotate(0deg);
    }
  }
  .label {
    cursor: pointer;
    flex: 1;
    height: 40px;
    background: #fff;
    border-radius: 6px;
    display: flex;
    align-items: center;
    transition: all 0.2s;
    padding: 0 12px;
    position: relative;
    z-index: 101; // 标签在最上层，确保可点击
    p {
      font-size: 20px;
      color: #585657;
      flex: 1;
    }
  }
  img {
    transform: rotate(180deg);
  }
  .slideCard {
    position: absolute;
    z-index: 99; // 默认层级
    width: 100%;
    left: 0;
    top: 30px;
    padding-top: 12px;
    pointer-events: none;
    opacity: 0;
    transition: all 0.2s;
    top: -20px;
    .inBox {
      border: 1px solid #eaeaea;
      background: #fff;
      border-radius: 10px;
      padding: 6px;
      display: flex;
      flex-direction: column;
      .list {
        display: flex;
        max-height: 250px;
        overflow-y: auto;
        flex-direction: column;
        &::-webkit-scrollbar {
          width: 6px;
        }
        &::-webkit-scrollbar-thumb {
          width: 6px;
          background: #b5e3cb;
          border-radius: 2px;
        }
      }
      .item {
        min-height: 42px;
        height: 42px;
        display: flex;
        align-items: center;
        padding: 0 12px;
        font-size: 20px;
        color: #a0a0a0;
        border-radius: 6px;
        transition: all 0.2s;
        &:hover {
          color: #fff;
          background: #46b97e;
        }
      }
    }
  }
}

.itemCard {
  margin-bottom: 20px;
  display: flex;
  flex-direction: column;
  .name {
    font-size: 20px;
    color: #585657;
    line-height: 32px;
    height: 32px;
    margin-bottom: 10px;
  }
  .input {
    width: 100%;
    height: 40px;
    padding: 0 12px;
    border: 1px solid #eaeaea;
    border-radius: 6px;
    font-size: 20px;
    color: #585657;
    box-sizing: border-box;
    &:focus {
      outline: none;
      border-color: #46b97e;
    }
    &::placeholder {
      color: #a0a0a0;
    }
  }
}

.rotateCard {
  display: flex;
  align-items: center;
  margin: 36px auto;
  .item {
    display: flex;
    flex-direction: column;
    align-items: center;
    .iconCard {
      width: 102px;
      height: 102px;
      background: url(@/assets/coordinate/icon8.svg);
      background-size: 100% 100%;
      position: relative;
      display: flex;
      align-items: center;
      justify-content: center;
      margin: 0 26px 20px;
    }
    &.on,
    &:hover {
      img {
        &.hov {
          opacity: 1;
        }
      }
    }
    &:nth-of-type(2) {
      .iconCard {
        transform: rotateY(180deg);
      }
    }
    img {
      width: 32px;
      height: 32px;
      &.hov {
        opacity: 0;
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translateX(-50%) translateY(-50%);
      }
    }
    p {
      font-size: 20px;
      color: #585657;
    }
  }
}

.saveCard {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  margin: 32px;
  .btn {
    border-radius: 6px;
    display: flex;
    align-items: center;
    width: 100px;
    height: 40px;
    justify-content: center;
    background: #46b97e;
    cursor: pointer;
    transition: all 0.2s;
    &:hover {
      background: #3da069;
    }
    img {
      width: 20px;
      margin-right: 8px;
    }
    p {
      font-size: 20px;
      color: #ffffff;
    }
  }
}
</style>
